# -*- coding: utf-8 -*-
"""GenAI_Assignment5 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Ae8bRzb228pGbGJ7k1WCWGPqjnm3YaI
"""

!pip install diffusers transformers accelerate torch torchvision safetensors

from diffusers import StableDiffusionPipeline
import torch

# Load the model
model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.to("cuda")  # Move model to GPU

# Generate an image
prompt = "A cat eating an apple"
image = pipe(prompt).images[0]
image.show()

from IPython.display import display

display(image)