# -*- coding: utf-8 -*-
"""assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpEhDKZllSvy5LO3vea0nTzPTcIMP09q
"""

!pip install transformers datasets torch accelerate

# Commented out IPython magic to ensure Python compatibility.
# %%writefile stories.txt
# A mysterious letter arrived at the boy’s doorstep one rainy evening.
# Deep beneath the ocean, a forgotten city slowly began to wake up.
# Every night at midnight, the clock in the old house started ticking backwards.
# A small dragon hatched in the most unexpected place, a school backpack.
# The traveler opened a door that shouldn’t have existed in the middle of the desert.
# In a quiet town, shadows started moving even when no one was there.

from transformers import GPT2Tokenizer, GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

model = GPT2LMHeadModel.from_pretrained("gpt2")

print("Model loaded successfully!")

from datasets import load_dataset

dataset = load_dataset("text", data_files={"train": "stories.txt"})

print(dataset)

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

tokenizer.pad_token = tokenizer.eos_token
tokenized_data = dataset.map(tokenize_function, batched=True)

from transformers import DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./gpt2_story_model",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    save_steps=500,
    save_total_limit=2,
    logging_steps=100,
    fp16=True
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_data["train"],
    data_collator=data_collator,
)

trainer.train()

model.save_pretrained("./my_story_model")
tokenizer.save_pretrained("./my_story_model")

print("Model Saved!")

from transformers import GPT2LMHeadModel, GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("./my_story_model")
model = GPT2LMHeadModel.from_pretrained("./my_story_model")

tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.eos_token_id

prompt = "Once upon a time"

inputs = tokenizer(
    prompt,
    return_tensors="pt",
    padding=True,
    truncation=True
)

input_ids = inputs["input_ids"].to(model.device)
attention_mask = inputs["attention_mask"].to(model.device)

output = model.generate(
    input_ids,
    max_length=200,
    temperature=0.8,
    top_k=50,
    top_p=0.9,
    do_sample=True
)

story = tokenizer.decode(output[0], skip_special_tokens=True)

print("Generated Story:\n")
print(story)